server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./demodb/sse_flux_server
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

sse-server:
  housekeeping:
    scheduler: "0 0/5 * * * ?"
    history-in-hours: 4 #keep historical sseEvents in database for the last n hours
