server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:./demodb/sse_flux_client
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

sse-server:
  url: http://localhost:8080/sse-server
